# wasmer.toml for CodeIgniter 4

# 1. Package Metadata
# Defines your application's name in the Wasmer registry.
[package]
name = "your-username/codeigniter-app" # IMPORTANT: Change this to your username and app name
version = "0.1.0"
description = "A CodeIgniter 4 application deployed on Wasmer Edge."

# Tells Wasmer this is a web application.
[package.kind]
http = {}

# 2. Base Environment
# We will use the official, modern PHP package from Wasmer as our base.
[dependencies]
php = "wasmer/php@^1.0.0"

# 3. Build & Install Steps
# These commands run on Wasmer's servers to prepare your app.
[build]
# This is the "Install Command". It downloads your Composer dependencies.
install-command = "COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader --ignore-platform-reqs"
# This is the "Build Command". It runs your database migrations after installation.
#build-command = "php spark migrate"

# 4. File System Mapping
# We map the entire local project directory (".") to a virtual "/app" directory inside the container.
# This ensures that Composer and Spark can find all necessary files.
[fs]
"/app" = "."

# 5. Run Command
# This tells Wasmer how to start the PHP server.
[[command]]
name = "run"
module = "wasmer/php:php"
runner = "wasi"

[command.annotations.wasi]
# This is the crucial part.
# We start the PHP server and point its document root (-t) to our public folder.
# The server will listen on all interfaces (0.0.0.0) on port 8080.
main-args = ["-t", "/app/public", "-S", "0.0.0.0:8080"]